name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: main

jobs:
  openjdk21:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Build project
        run: sbt compile

      - name: Test project
        run: sbt "database/test"

      - name: Check Formatting
        run: sbt scalafmtAll
